// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstyTlH33Et40wF5h2EuX8ebGLWgIjAAk',
    appId: '1:325346120140:web:5c86817220240869968d69',
    messagingSenderId: '325346120140',
    projectId: 'facecheck-e6e81',
    authDomain: 'facecheck-e6e81.firebaseapp.com',
    storageBucket: 'facecheck-e6e81.firebasestorage.app',
    measurementId: 'G-4RP7B9BLN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rsjZI1fsFR6_s0utYOgC-nUYXom2aU0',
    appId: '1:325346120140:android:6b0ad1087395fb1d968d69',
    messagingSenderId: '325346120140',
    projectId: 'facecheck-e6e81',
    storageBucket: 'facecheck-e6e81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7y9IjaPf-gY6oJ6FhvsWoJAbFlzNC2VA',
    appId: '1:325346120140:ios:a18c35f4330a63d1968d69',
    messagingSenderId: '325346120140',
    projectId: 'facecheck-e6e81',
    storageBucket: 'facecheck-e6e81.firebasestorage.app',
    iosBundleId: 'com.example.appteste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7y9IjaPf-gY6oJ6FhvsWoJAbFlzNC2VA',
    appId: '1:325346120140:ios:a18c35f4330a63d1968d69',
    messagingSenderId: '325346120140',
    projectId: 'facecheck-e6e81',
    storageBucket: 'facecheck-e6e81.firebasestorage.app',
    iosBundleId: 'com.example.appteste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDstyTlH33Et40wF5h2EuX8ebGLWgIjAAk',
    appId: '1:325346120140:web:5c86817220240869968d69',
    messagingSenderId: '325346120140',
    projectId: 'facecheck-e6e81',
    authDomain: 'facecheck-e6e81.firebaseapp.com',
    storageBucket: 'facecheck-e6e81.firebasestorage.app',
    measurementId: 'G-4RP7B9BLN2',
  );
}
